-- AlterTable
ALTER TABLE `Car` ADD COLUMN `vin` VARCHAR(191) NULL,
ADD COLUMN `trackerLogin` VARCHAR(191) NULL,
ADD COLUMN `trackerPassword` VARCHAR(191) NULL,
ADD COLUMN `trackerUrl` VARCHAR(191) NULL,
ADD COLUMN `trackerNotes` VARCHAR(2000) NULL;
